services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app/
    env_file:
      - .env
    depends_on:
      - chromadb
    # command: python main.py --scrape-and-inject
    # command: sleep infinity

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - 8000:8000
    volumes:
      - index_data:/chroma/.chroma/index

volumes:
  index_data:
    driver: local